---

- hosts: cluster
  gather_facts: False
  roles:
    - coreos

# If an existing etcd cluster exists then any changes to the etcd_cluster group
# should probably use the same etcd discovery url. Pass etcd_discovery_url as
# an extra var or a new etcd service will form an independent cluster.
- hosts: etcd_cluster
  vars:
    # need_bootstrap is registered by the coreos role.
    new_cluster: "{{need_bootstrap.rc > 0}}"
    # new_cluster: true
  roles:
    - etcd

#
# - hosts: k8s_cluster
#   roles:
#     - kubernetes
#
# - hosts: k8s_master
#   roles:
#     - kubernetes_master
#
# - hosts: k8s_minions
#   roles:
#     - kubernetes_minion

- hosts: cluster
  roles:
    - cloud-config
