---

# - name: debug
#   local_action: debug msg="new_cluster <{{new_cluster}}> etcd_discovery_url <{{etcd_discovery_url|default('undef')}}>"

# Note: This is an external dependancy and requires HTTPS outbound for local and remote instances
# We're assuming the if the cluster has been bootstrapped then a new
# token for etcd is needed, unless an extra_var has been provided
- name: Get etcd discovery token from discovery.etcd.io
  run_once: true
  local_action: uri url=https://discovery.etcd.io/new return_content=yes
  register: etcd_discovery_token
  when: new_cluster and etcd_discovery_url is not defined

- name: Configure etcd
  set_fact:
    etcd_public_addr: "{{ hostvars[ansible_hostname]['ansible_'+public_iface]['ipv4']['address'] }}"
    etcd_peer_addr: "{{ hostvars[ansible_hostname]['ansible_'+private_iface]['ipv4']['address'] }}"
    etcd_discovery_url: "{{ etcd_discovery_token.content|default(etcd_discovery_url|default('')) }}"

- name: Fail if no discovery url
  run_once: true
  local_action: fail msg="No discovery url for etcd cluster configuration"
  when: etcd_discovery_url==""

- name: Record etcd cluster started with discovery url
  run_once: true
  local_action: debug msg="The etcd service will be started with etcd_discovery_url {{etcd_discovery_url}}"
  when: etcd_discovery_url!=""
