---

# Note: This is an external dependancy and requires HTTPS outbound for local and remote instances
# We're assuming the if the cluster has been bootstrapped then a new
# token for etcd is needed, unless an extra_var has been provided
- name: Get etcd discovery token from discovery.etcd.io
  run_once: true
  local_action: uri url=https://discovery.etcd.io/new return_content=yes
  register: etcd_discovery_token
  when: new_cluster==true and etcd_discovery_url==''
